parameters:
    rid.page.document.page.class: Rid\Bundle\PageBundle\Entity\Page
    rid.page.repository.page.class: Rid\Bundle\PageBundle\Entity\RepositoryPage
    rid.page.admin.page.class: Rid\Bundle\PageBundle\Admin\PageAdmin
    rid.page.document.page.class: Rid\Bundle\PageBundle\Entity\Page
    rid.page.document.repository.class: Rid\Bundle\PageBundle\Entity\PageRepository
    rid_page.class: Rid\Bundle\PageBundle\Services\RidPageManager
    rid.page.twig_extension.page.class: Rid\Bundle\PageBundle\Twig\RidPageExtension

services:
    rid.page.admin.page:
        class: %rid.page.admin.page.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: rid_page_group, label: 'rid_page.db_label', label_catalogue: "RidPageBundle" }
        arguments:
            - ~
            - %rid.page.document.page.class%
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [RidPageBundle]]

    rid.page.repository.page:
        class:            "%rid.page.repository.page.class%"
        factory_service:  doctrine.orm.entity_manager
        factory_method:   getRepository
        arguments: [ %rid.page.document.page.class% ]

    rid_page:
        class: %rid_page.class%
        calls:
            - [ setRepository, [@rid.page.repository.page]]

    rid.page.twig_extension.page:
        class: %rid.page.twig_extension.page.class%
        tags:
            - { name: twig.extension }
        calls:
            - [ setManager, [ @rid_page ] ]